<?php
  register_post_type( 'style-guide', array(
  'labels'            => array(
    'name'                => __( 'Style Guides', 'soup2nuts' ),
    'singular_name'       => __( 'Style Guide', 'soup2nuts' ),
    'all_items'           => __( 'All Style Guides', 'soup2nuts' ),
    'new_item'            => __( 'New Style Guide', 'soup2nuts' ),
    'add_new'             => __( 'Add New', 'soup2nuts' ),
    'add_new_item'        => __( 'Add New Style Guide', 'soup2nuts' ),
    'edit_item'           => __( 'Edit Style Guide', 'soup2nuts' ),
    'view_item'           => __( 'View Style Guide', 'soup2nuts' ),
    'search_items'        => __( 'Search Style Guides', 'soup2nuts' ),
    'not_found'           => __( 'No Style Guides found', 'soup2nuts' ),
    'not_found_in_trash'  => __( 'No Style Guides found in trash', 'soup2nuts' ),
    'parent_item_colon'   => __( 'Parent Style Guide', 'soup2nuts' ),
    'menu_name'           => __( 'Style Guide', 'soup2nuts' ),
  ),
  'public'            => true,
  'hierarchical'      => true,
  'show_ui'           => true,
  'show_in_nav_menus' => false,
  'supports'          => array( 'title', 'editor', 'thumbnail', 'page-attributes' ),
  'has_archive'       => false,
  'rewrite'           => true,
  'query_var'         => true,
  'publicly_queryable' => true,
  'exclude_from_search' => true,
  'menu_icon'         => 'dashicons-admin-customizer',
  'show_in_rest'      => false,
  'rest_base'         => 'style-guide',
  'rest_controller_class' => 'WP_REST_Posts_Controller',
  ) );
